# Generated by Django 3.2.5 on 2021-09-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total2',
        ),
    ]
